// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5NllAK9CuvJVKI1J9B8PAP4g_8W8eYr8',
    appId: '1:922700997410:web:fbe3b0dd9fe01ced2f7b7b',
    messagingSenderId: '922700997410',
    projectId: 'eui-expense-tracker',
    authDomain: 'eui-expense-tracker.firebaseapp.com',
    storageBucket: 'eui-expense-tracker.firebasestorage.app',
    measurementId: 'G-N6N6L5RWXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTs0rgHANpS60PqyqPVgzau97zrU_mxk',
    appId: '1:922700997410:android:ef98cfcad1857a2c2f7b7b',
    messagingSenderId: '922700997410',
    projectId: 'eui-expense-tracker',
    storageBucket: 'eui-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzCBsys6OpsJ1kX4TYCbe4Os1R5inPoHM',
    appId: '1:922700997410:ios:a4a4d6755f4502782f7b7b',
    messagingSenderId: '922700997410',
    projectId: 'eui-expense-tracker',
    storageBucket: 'eui-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzCBsys6OpsJ1kX4TYCbe4Os1R5inPoHM',
    appId: '1:922700997410:ios:a4a4d6755f4502782f7b7b',
    messagingSenderId: '922700997410',
    projectId: 'eui-expense-tracker',
    storageBucket: 'eui-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5NllAK9CuvJVKI1J9B8PAP4g_8W8eYr8',
    appId: '1:922700997410:web:e2b52bb1b4a4db6e2f7b7b',
    messagingSenderId: '922700997410',
    projectId: 'eui-expense-tracker',
    authDomain: 'eui-expense-tracker.firebaseapp.com',
    storageBucket: 'eui-expense-tracker.firebasestorage.app',
    measurementId: 'G-9744K40LM7',
  );
}
